import java.lang.Exception

//MITHA ZALINA RAMADHANY
//RPL 5A
fun main(args: Array<String>) {
    try{
        val myVar:Int = 10;
        val v:String = "Rekayasa Perangkat Lunak";
        v.toInt()
    }catch (e:Exception){
        e.printStackTrace()
    }finally {
        println("Exception Handeling in Kotlin")
    }
}